Change calloc() so it passes Widnows build test
Code compiles under linux (not tested yet, I have no proxmark available right now)
Previous commit fails windows build test with:

src/cmdhfmfu.c: In function 'CmdHF14AMfuESave':
src/cmdhfmfu.c:4220:19: error: array subscript 'mfu_dump_t[0]' is partly outside array bounds of 'mfu_dump_t[0]' [-Werror=array-bounds]
 4220 |         end = dump->pages ;
      |                   ^~
In function 'GetMfuDumpFromEMul',
    inlined from 'CmdHF14AMfuESave' at src/cmdhfmfu.c:4202:15:
src/cmdhfmfu.c:4105:21: note: object of size 1076 allocated by 'calloc'
 4105 |     uint8_t *dump = calloc(MFU_MAX_BYTES + MFU_DUMP_PREFIX_LENGTH, sizeof(uint8_t));
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~