lz4/fpga_compress: remove warning missing-braces
fpga_compress.c:154:49: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    LZ4_streamDecode_t lz4StreamDecode_body = { 0 };
                                                ^
                                                {}